### ISSUE TITLE
Erroneous instruction for Lab

### ISSUE THREAD

**Issue by neugierige** [ga-wdi-boston/git-workflow-teams#25] opened 2016-12-06 20:17 UTC
Under the [Lab](https://github.com/ga-wdi-boston/git-workflow-teams#lab--using-the-ga-group-project-workflow) section:

> You may start by downloading the JS-Template as a ZIP and dropping those files into your repo. 

First of all, `JS-Template` is the wrong name. Secondly, this conflicts with the instructions on the Browser Template [README](https://github.com/ga-wdi-boston/browser-template/blob/master/README.md).

**Comment by BenGitsCode** [comment] 2017-02-22 15:22
This is a duplicate of #24

**Closed as completed by BenGitsCode** 2017-02-22 15:22 UTC
